on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Ensure scripts are executable
        run: chmod +x script/cibuild script/bootstrap

      - name: Lint & Autocorrect
        run: bundle exec rubocop -A  

      - name: build
        run: script/bootstrap

      #- name: test
      #  run: script/cibuild